### ISSUE TITLE
[ISSUE] seq로 스크립트 분석

### ISSUE THREAD

**Issue by HYEOK9** [khu-capstone-design-case/case-backend#10]
`/api/user/page/script` get에 body..? get에 body는 안씀!!
내가 저번에 말을 헷갈리게 했나보네 미안쓰

- 유저가 정의한 값이 엔드포인트에 들어가면 안좋다한건 `/talker?opponent=김진호`보다 `/talker?opponentId=8`가 좋다고 한거
- 위의 경우는 number[]로 값이 정해져있어서 상관 없음 post로 바꾸거나 req query로 부탁ㅎㅎㅎ,,,,
- 그리고 req param이랑 query랑은 다릅니다 [참고](https://dar0m.tistory.com/222)

++ `GET /api/user/page/script`랑 `POST /api/script`랑 뭐가 다른거야? 테스트해서 안된건 후자엿음

**Comment by lomayd** [comment]
확인했음

GET /api/user/page/script 이거는 프론트엔드 request - 백엔드 response 를 위한 API
POST /api/script 이거는 백엔드 request- AI response 를 위한 API
정상 동작 테스트 완료했음
