### ISSUE TITLE
auth 관련 issue

### ISSUE THREAD

**Issue by HYEOK9** [khu-capstone-design-case/case-backend#3]
/api/user/login
-> 응답으로 accessToken에 더해서 userId 반환하면 좋을듯 
-> 도메인 다르면 쿠키가 안가므로 refreshToken은 올 수 없음
-> 그리고 굳이 refreshToken필요 없어보임

/api/user/join
-> 마찬가지로 회원가입 성공했을 때 id, token 응답으로 주면 로그인 한 번 더 할 필요없음 (근데 이건 기능상 문제는X)
-> status 안옴

**Comment by lomayd** [comment]
/api/user/login
-> 응답으로 accessToken, id(기존 코드상 id가 더 적절하다고 판단) 반환되도록 수정 완료
-> 도메인이 다를 때 쿠키가 안 가는 것은 CORS 설정 잘하면 쿠키 가는 것으로 알고 있음(저번 프로젝트 때 확인도 했었음)
-> 보다 완성도 있게 하기 위해 refreshToken 사용했음

/api/user/join
-> 혼동 방지를 위해 Notion에 있는 API 명세서에 status 부분 전부 삭제함

**Comment by HYEOK9** [comment]
1. 그럼 cors설정 부탁드립니당 sameSite None + secure 쿠키로.. 권장되는 방식은 아님

2. 쿠키만료인 경우 expired 응답이 따로 오고 있나? 비로그인이랑 똑같이 40x unAuthorized 왔던 거 같아서... 요런거 명세 있으면 좋음!

**Comment by lomayd** [comment]
1. 기본적인 CORS 설정 적용되고 있는데 그래도 안 보내지면 디스코드 화면공유 등을 통해 확인해야 할 듯
- samesite=none - 기존 쿠키 전송 방식과 동일(서브 도메인 쿠키 설정 이런 부분이여서 본 프로젝트와 상관없음)
- secure - https가 적용된 요청에만 전송가능(본 프로젝트에는 https 적용하지 않기 때문에 상관 없음)

2. 쿠키 만료의 경우 따로 만료되었다는 응답은 없고 기존처럼 401 unauthorized 뜸

**Comment by HYEOK9** [comment]
음... sameSite none 해야 다른 도메인간 쿠키 전송 가능한걸로 알고있는데🧐 그리고 이미 secure해놓은거 아님..?

<img width="918" alt="image" src="https://github.com/khu-capstone-design-case/case-backend/assets/87190744/0d9945b2-fcc7-4213-b013-551eedbf0a22">

1. https+same site none + secure
2. http + same site none

뭘로 하고싶은거야? 프론트는 로컬에 ssl붙여서 개발/배포 둘다 가능해서 맞출수 있음
근데sameSite none에 secure까지 안붙이면 보안되게 안좋은 걸로 알고있음

++ 2번 질문의 의미는 비로그인/쿠키만료 상태가 똑같이오면 refreshToken을 요청 타이밍을 모른다는 거였음!
-> 음 얘는 프론트에서 알아서 처리할게요 auth에 시간 쏟는거 별로인 거 같아서

**Comment by lomayd** [comment]
리서치해보니까 samesite의 default값이 lax(서브 도메인 쿠키 설정 X, 몇몇 예외사항 있음)여서 안 보내진것 같고,

개발 기한이 얼마 남지 않으므로 일단 http + samesite none으로 설정해놓고 나중에 수정할 시간 있으면 수정하겠음
