### ISSUE TITLE
/api/user/page

### ISSUE THREAD

**Issue by HYEOK9** [khu-capstone-design-case/case-backend#4]
<img width="387" alt="image" src="https://github.com/khu-capstone-design-case/case-backend/assets/87190744/27def9c8-5bfd-42a4-9cee-3f586ab10e9a">

음성파일 post 후 메인 페이지 fetch 했는ㄴ데 talker 배열이 비어있는건 AI안 붙인 상태여서인가?????????????????

**Comment by lomayd** [comment]
맞음

프론트엔드 서버에서 음성 파일 업로드 -> 백엔드 서버에서 음성파일 분석을 위해 AI 서버의 API를 호출 -> AI 서버의 response 결과 데이터를 받아 DB에 저장

아직 AI서버의 API가 완전히 구현되지 않았기 때문에 다음과 같은 결과가 나왔음

**Comment by HYEOK9** [comment]
확인
