### ISSUE TITLE
바라는 . (바라는 점이란 뜻)

### ISSUE THREAD

**Issue by HYEOK9** [khu-capstone-design-case/case-backend#5]
issue는 아니고 의견!!
<img width="583" alt="image" src="https://github.com/khu-capstone-design-case/case-backend/assets/87190744/7ba55321-0636-4645-9ed0-39e200cd6e45">
1. 이런식으로 에러에 status랑 메시지 오는건 매우 좋은데❗️ 명세서에 안적혀 있어서 모든 에러 하나씩 체험 하면서 개발 중
(중복된 아이디로 가입하는 경우 UI로 유저에게 알려줘야하기 때문에)

2. 그리고 성공이든 실패든 response가 일관성이 있으면 좋을듯
성공일 경우 { status:200, message: "successfully 어쩌구" , data: ~~}
실패일경우 { status:400, message: "unAuthorized", data: ~~}
이런식으로? 왜냐면 프론트에서 response type을 정해놓고 api를 보내는데 응답마다 dto가 달라서 정의하기가 애매함

3. 엔드포인트가 유저가 정의한 값이면 안됨!! 유저가 이상한 문자 (/, 특수문자, 한글) 같은 거 입력하면 인코딩 해야되는데 변수 되게 많음 이거
<img width="623" alt="image" src="https://github.com/khu-capstone-design-case/case-backend/assets/87190744/3f63f501-83cd-475e-8eae-fa6d27d13673">

**Comment by lomayd** [comment]
1. 예외처리를 명세하라
2. 모든 response data를 일관되게 작성하라
3. 모든 데이터는 request body에 작성하라 (request-param, pathvariable 말고)

확인했음
프론트엔드 인원이랑 논의 결과 지금은 시간상 수정이 어려워 코드는 그대로 가나, 이후 프로젝트에서 개선 예정
