### ISSUE TITLE
[issue] 쿠키

### ISSUE THREAD

**Issue by HYEOK9** [khu-capstone-design-case/case-backend#6]
~~25일까지 음성 파일 업로드 잘 됐는데 pull 받은 이후로 아래와 같은 에러남~~
-> ai 이슈인거 확인

그리고 이건 나도 몰랐는데 sameSite None인데 secure안붙으면 크롬자체에서 쿠키를 차단해버림 sameSite None+secure주셈 http여도 쿠키 오는거 확인함~

**Comment by lomayd** [comment]
확인했음
issue #7 에서 수정 예정
