### ISSUE TITLE
필요한 거

### ISSUE THREAD

**Issue by HYEOK9** [khu-capstone-design-case/case-backend#7]
1. 쿠키 secure true
2. GET `/api/user/page`, `/api/user/page/talker`에서 총 통화시간/통화별 통화한시간 보내 줄수있는지?
3. GET `/api/user/page`, `/api/user/page/talker`에서 총 점수 (50 + positive - negative) 보내주세요~

**Comment by lomayd** [comment]
전부 기능 수정 및 추가했음

DB상에 새로운 필드 추가했으므로 DB 초기화 후 진행하는 것을 권장함
