### ISSUE TITLE
/api/script

### ISSUE THREAD

**Issue by HYEOK9** [khu-capstone-design-case/case-backend#8]
<img width="690" alt="image" src="https://github.com/khu-capstone-design-case/case-backend/assets/87190744/1f94ffd6-4eb4-45bf-a143-d9551879a7c8">

array까지 받는건 진짜 아닌듯 심지어 post인데😵
바디로 받읍시다 쿼리 왤케 좋아함ㅋㅋ

**Comment by lomayd** [comment]
원래 다 request-body로 짜다가 dto 구성할 때 변수 하나만 있는 것들도 있어서 request-param으로 받은 거임....

수정 했음
