### ISSUE TITLE
[중요] 이름 관련 issue

### ISSUE THREAD

**Issue by HYEOK9** [khu-capstone-design-case/case-backend#9]
## 상황
- 혹시 이름을 key로 사용하고 있나요
- 회원가입, 업로드 트랜잭션에 이름값 잘못 물려있는 듯
## 에러내용
- 중복된 이름으로 회원가입 안되서 동명이인 서비스 이용 불가
- 예를들어 서로다른 유저가 "김진호"라는 사람과 통화하면 한명꺼에만 반영됨
- 서로 다른 유저가 "김진호"와 통화내역을 삭제 후 다른 유저가 "김진호"와의 대화 업로드하면 해당 column생성도 안되는듯
- 이 외에도 더 많은 버그 있을 것으로 보임
## 테스트 환경
710a03a1a8649c2adbc5cc950288ecbec98f552e

## 아 참
- 유저 조회기능 있어야함
- 일단 refreshToken주는 api로 대체할테니 여기 이름도 보내주세요오오오
- 필요한 이유: 채팅 보여줄때 본인인지 상대인지 이름값으로 결정되고 기본적으로 필요한 기능이기도함

**Comment by lomayd** [comment]
음성파일, 스크립트 관련 DB(MongoDB)의 user 필드 이름 -> 아이디(이메일)로 변경함

다만, 스크립트 조회 시 통화자가 아이디(이메일)로 보이는 문제가 있으므로 프론트엔드에서 수정 필요

로그인, 토큰 재발급 API response body에 accessToken, id, name 넣었음
